# Generated by Django 5.0.4 on 2024-07-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Email', models.EmailField(max_length=100, verbose_name='Email')),
                ('Number', models.IntegerField(max_length=10, verbose_name='Number')),
            ],
        ),
    ]
