# Generated by Django 5.0.4 on 2024-07-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Number',
            field=models.IntegerField(verbose_name='Number'),
        ),
    ]
