# Generated by Django 5.0.4 on 2024-07-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_employee_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Number',
        ),
    ]
